"""users.about_me

Revision ID: 052b080d4ca6
Revises: 0fe7149de2ab
Create Date: 2019-07-19 16:31:57.232825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052b080d4ca6'
down_revision = '0fe7149de2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_Seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_Seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
