"""users.last_seen

Revision ID: 82e8bd0e1319
Revises: 052b080d4ca6
Create Date: 2019-07-19 17:22:09.978287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82e8bd0e1319'
down_revision = '052b080d4ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.drop_column('user', 'last_Seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_Seen', mysql.DATETIME(), nullable=True))
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
